fastlane_version "2.14.2"

default_platform :ios

platform :ios do
  before_all do
    clear_derived_data(derived_data_path: "./DerivedData")
  end

  desc "Runs setup"
  lane :setup do
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      scheme: "ScreenShotExample",
      device: "iPhone 7 Plus (10.2)",
      derived_data_path: "./DerivedData",
      skip_build: true,
      include_simulator_logs: false, # workaround for 2.14.2
      clean: true
    )

    slather(
      proj: "ScreenShotExample.xcodeproj",
      scheme: "ScreenShotExample",
      build_directory: "./DerivedData",
      output_directory: "./fastlane/test_output/slather",
      html: true
    )
  end
end
